### ISSUE TITLE
[Tracking Issue] Pass the rest of integration tests

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#252]
Excluding the tests are also failing with `runc`, here are the rest that we have not investigated. Let's finish this :)

- [x] "linux_process_apparmor_profile/linux_process_apparmor_profile.t #300 
- [x] "linux_rootfs_propagation/linux_rootfs_propagation.t" #256 
- [x] "linux_seccomp/linux_seccomp.t" #25 
- [x] "linux_uid_mappings/linux_uid_mappings.t" #255 
- [x] "mounts/mounts.t" #249 
- [x] "linux_masked_paths/linux_masked_paths.t" #227 
- [x] "pidfile/pidfile.t" #250 
- [x] "process_oom_score_adj/process_oom_score_adj.t" #246 
- [x] "process_user/process_user.t" #239

**Comment by Furisto** [comment]
I can take a look at the apparmor test.

**Comment by utam0k** [comment]
I'd like to make something relatively simple as a good first issue.

**Comment by yihuaf** [comment]
> I'd like to make something relatively simple as a good first issue.

Absolutely. The goal for this is to track what's left. seccomp and apparmour likely will require some effort. Maybe uid_mapping and rootfs propagation can be a good first issue.
