### ISSUE TITLE
[Tracking Issue] Improve the test coverage

### ISSUE THREAD

**Issue by utam0k** [containers/youki#8]
The current youki has far too few unit tests.
We are planning to increase the test coverage for the following files.
Perhaps this is a very good opportunity to understand the code and how it works. If you are interested, please comment on the issue and declare the files you want to test.

- [ ] `src/spec.rs`
- [ ] `src/namespaces`
- [x] `src/cgrpups/devices.rs`(assigned @tsturzl) https://github.com/containers/youki/pull/75
- [ ] `src/cgroups/manage.rs`
- [ ] `src/create.rs`(assigned @TinySong)
- [ ] `src/capability.rs` (assigned @sensaiankit)
- [ ] `src/rootfs.rs`(assigned @constreference )
- [x] `src/tty.rs`(assigned @constreference ) https://github.com/containers/youki/pull/102

**Comment by constreference** [comment]
Hi, @utam0k  I"d be happy to take capability and tty

**Comment by utam0k** [comment]
@constreference 
Thanks for your interest!  Sorry, the `capability.rs` was already assigned to @sensaiankit  through a DM exchange. I forgot to update it.
`tty.rs` is definitely something you should do, but it is the least maintained and may need refactoring. It may be a bit of a challenge, but I'd love to see it done.
Can I assign `tty.rs` to you?

**Comment by constreference** [comment]
Sure !, I'll give it a shot !

**Comment by utam0k** [comment]
I assigned it to you. Looking forward to your PR!

**Comment by tsturzl** [comment]
I can take the device cgroup controller testing. I'll just implement the same tests I had done on the other controllers.

**Comment by utam0k** [comment]
@tsturzl Ok! I assigned you.

**Comment by TinySong** [comment]
@utam0k I would like to take ` src/create.rs` or `src/namespaces` tests

**Comment by utam0k** [comment]
@TinySong Thanks for your interest!
I'd love to have you do the `create.rs`, but it might be a bit challenging. If you have the time and seem to be quite interested, I'd like to ask you to do `create.rs`. This will be the core youki file.

**Comment by TinySong** [comment]
@utam0k yeah, I love to take that. If i encounter difficulties, I will ask you again，thanks

**Comment by utam0k** [comment]
@TinySong Sure. I assigned you to `create.rs`.

**Comment by constreference** [comment]
@utam0k I would like to take rootfs !

**Comment by utam0k** [comment]
@constreference Of course. I'm looking forward to working with you.

**Comment by utam0k** [comment]
Yuki's codes have changed a lot, so I'll close it once.
