### ISSUE TITLE
[Tracking Issue] Support for cgroups v1

### ISSUE THREAD

**Issue by utam0k** [containers/youki#9]
This issue is for tracking the implementation of [cgroups](https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt).
Since devices of cgoups has already been implemented, you can implement it while referring to it.
If you are interested, you can comment on this issue and I will assign it to you.

- [x] devices
- [x] network(assigned @tsturzl)
The integration test is this: https://github.com/opencontainers/runtime-tools/tree/master/validation/linux_cgroups_network
- [x] pids (assigned @0xdco) https://github.com/utam0k/youki/pull/26
- [x] hugepageLimits(assigned @Furisto) https://github.com/utam0k/youki/pull/15
- [x] memory (assigned @tsturzl) https://github.com/utam0k/youki/pull/16
- [x] cpu(assigned @Furisto) https://github.com/containers/youki/pull/63
The integration test is this: https://github.com/opencontainers/runtime-tools/tree/master/validation/linux_cgroups_cpus
- [x] blockIO(assigned @Furisto) https://github.com/utam0k/youki/pull/31
- [x] cpuacct (assigned @yjuba) https://github.com/containers/youki/pull/92
- [x] cpuset (assigned @Furisto) https://github.com/containers/youki/pull/63
- [x] perf_event (assigned @fbrv) https://github.com/containers/youki/pull/166
- [x] freezer (assigned @duduainankai ) https://github.com/containers/youki/pull/93

# Goal
Each of them will be targeted to pass integration tests. If possible, it is good to have unit tests as well.
It would be helpful to have a look at the GitHub Actions file to see how to run the integration tests.

# Reference
- https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#control-groups
- https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/index.html

**Comment by sensaiankit** [comment]
I would like to work on this issue, but as I am a beginner i didn't understood the issue so can you please guide me

**Comment by 0xdco** [comment]
Hi @utam0k, thanks for your work so far! I'm looking for some tasks to hone my Rust skills and I guess this issue looks like a perfect candidate, I'm interested in the assignment. I'll go through the [cgroups](https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt) to check the details, but I guess it would be beneficial to all if we could somehow have a in depth implementation discussion to better align with your vision of the project. You can DM me on Twitter: [`@0xd___`](https://twitter.com/0xd___).

**Comment by utam0k** [comment]
@sensaiankit How about this issue(https://github.com/utam0k/youki/issues/8), which is more recommended for beginners?
For example, `src/namespaces` already has one sample test, so you can use that as an example to increase.

**Comment by utam0k** [comment]
@0xdco Thanks! I'd like to assign you to one of cgroup's controller.
Which controller are you most interested in?
Or do you want to modify or refactor the architecture?  If you have any advice on architecture or code I'd love to hear it :)

**Comment by sensaiankit** [comment]
> @sensaiankit How about this issue(#8), which is more recommended for beginners?
> For example, `src/namespaces` already has one sample test, so you can use that as an example to increase.

Okay cool looking forward for that issue. I still would like to get guidance from you, would you mind connecting somewhere like either twitter or discord

**Comment by utam0k** [comment]
@sensaiankit Of course! If you want my guidance you can contact me on Twitter DM. I will do my best to accommodate you as my time permits. Sorry if it takes me a while to reply.

**Comment by sensaiankit** [comment]
> @sensaiankit Of course! If you want my guidance you can contact me on Twitter DM. I will do my best to accommodate you as my time permits. Sorry if it takes me a while to reply.

I saw your twitter account but i cant really do a dm will you please open it ?

**Comment by utam0k** [comment]
> > @sensaiankit Of course! If you want my guidance you can contact me on Twitter DM. I will do my best to accommodate you as my time permits. Sorry if it takes me a while to reply.
> 
> I saw your twitter account but i cant really do a dm will you please open it ?

Sorry... I opened it.

**Comment by 0xdco** [comment]
> 
> 
> @0xdco Thanks! I'd like to assign you to one of cgroup's controller.
> Which controller are you most interested in?
> Or do you want to modify or refactor the architecture? If you have any advice on architecture or code I'd love to hear it :)

You can assign me to whichever controller you think is a good easy / introductory point to the project as I'm still reading the code and the documentation(s) to get started. I will be able to start tackling it during the weekend. Depending on how successful I am in my endeavor, I might take over other available controllers to write as well. I have no plans to modify or refactor the architecture but let's see after the implementation if there are opportunities to do some cleanups.
I'm also taking a look in the railcar implementation in the hope it gives me some insights on how to implement it on youki.
Furthermore, it would be awesome if you could point me out to any resource on how to test / check the changes as I'm not quite familiar with runc nor runtime-spec (taking a look at it already).

**Comment by utam0k** [comment]
@0xdco 
I assigned you to the pids of the controller. I'm thinking that it's probably not that difficult.
How about using this test provided by the opencontainers to guarantee operation? (You can test this by setting an environment variable called RUNTIME in the youki exec file.)
https://github.com/opencontainers/runtime-tools/tree/master/validation/linux_cgroups_pids
runtime-spec's document about groups is here.
 https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#control-groups

It is a very good idea!
> I'm also taking a look in the railcar implementation in the hope it gives me some insights on how to implement it on youki.

**Comment by reynn** [comment]
Can I be assigned the CPU and/or Memory, any tips you may already know of would be awesome but should be able to handle either way!

**Comment by utam0k** [comment]
@reynn 
Thanks for your interest!
I would like to assign the CPU of the controller to you. If you finish soon, I may assign another. to you.
I look forward to your PR.

**Comment by tsturzl** [comment]
I'd be happy to take the memory cgroup controller.

**Comment by tsturzl** [comment]
this is another great resource for everyone: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/index.html

**Comment by utam0k** [comment]
@tsturzl 
Thanks for your interest. Of course, I assigned it to you.
> I'd be happy to take the memory cgroup controller.

I think so too. That's why I'm making this issue a `good first issue`.
> Basically the cgroup controller is configured by interaction with a virtual filesystem. You're basically just writing specific things to certain files in a certain directory. The implementation for these should be relatively easy and straightforward for each of these once you know what needs to go where. Happy hacking!

**Comment by Furisto** [comment]
I would like to work on the hugepage cgroup controller.

**Comment by utam0k** [comment]
@Furisto 
Sure! I assigned you. I am sincerely waiting for your PR.

**Comment by tsturzl** [comment]
I can go ahead an take the network controller on. The memory controller PR is just waiting to be merged after I integrate with the changes @Furisto made. I can probably be finished up with the network controller by Monday.

**Comment by utam0k** [comment]
@tsturzl 
Your work is amazing! 
Okay, I'll assign you to it. I don't intend to rush it, so it would be great if you could proceed. I am sincerely waiting for your PR.

**Comment by 0xdco** [comment]
I'm happy to take another controller if there is still any available :)

**Comment by Furisto** [comment]
I have started with the blkio controller. Can you assign me @utam0k ?

**Comment by utam0k** [comment]
@0xdco 
Sorry, the blockio controller has already started by @Furisto. So, All of the controller issues have been filled.
Your PR is so great, why don't you try https://github.com/utam0k/youki/issues/24 or supporting cgroups v2 instead, which is a bit of a challenge?
If you want to make it a little less difficult, you can make it so that other integration tests will pass.
For example, you can challenge the create integration test (https://github.com/opencontainers/runtime-tools/tree/master/validation/create). Of course, you can also challenge other integration tests such as start and kill.
> I'm happy to take another controller if there is still any available :)

**Comment by utam0k** [comment]
@Furisto Ok, I assigned it to you.
> I have started with the blkio controller. Can you assign me @utam0k ?

**Comment by 0xdco** [comment]
> 
> 
> @0xdco
> Sorry, the blockio controller has already started by @Furisto. So, All of the controller issues have been filled.
> Your PR is so great, why don't you try #24 or supporting cgroups v2 instead, which is a bit of a challenge?
> If you want to make it a little less difficult, you can make it so that other #27.
> 
> > I'm happy to take another controller if there is still any available :)

All fine! I'll start with #27 to keep me busy just right now. I'm really interested in cgroups v2, and it is indeed more challenging (I'll review the doc this week), so it would be nice to have a tracking issue for cgroups v2 implementation so that we can discuss the implementation details and track it.

**Comment by Furisto** [comment]
@utam0k 
I can take over the cpu controller

**Comment by utam0k** [comment]
@Furisto Thanks! Sure, I assigned it to you.

**Comment by utam0k** [comment]
This issue was completed!
Special thanks @0xdco @reynn @tsturzl @Furisto

**Comment by tsturzl** [comment]
@utam0k @reynn Are we missing the CPU Accounting subsystem? Is this something we intended to support?

**Comment by utam0k** [comment]
@tsturzl Is this https://github.com/containers/youki/pull/63?

**Comment by tsturzl** [comment]
@utam0k You're right, they aren't present in the runtime-tools test suite, however I do see them implemented in runc. We do not implemented cpuacct, prefevent, or freezer which are all implemented by runc. I'm not sure how important or useful they are, or if they're worth including, I just noticed they were implemented in runc but we don't currently have them. It's easy enough to write new controllers, if we want to include them just to be as feature complete as possible. @Furisto seems to have a pretty good grasp on cgroups, and I think his input would be really valuable here. Should we implement these controllers?

**Comment by utam0k** [comment]
@tsturzl @Furisto  For example, in response to this, how about leaving it for first contributors? You two are very talented and probably know more than enough to deal with this. I'd love to have you guys around to review, what do you think?
Of course, if no one shows up in the immediate future to do it, we can all deal with it together.

**Comment by Furisto** [comment]
@utam0k @tsturzl 
The cpuset controller was implemented with #63. I think cpuacct and perf_event make sense to implement and basically only require to write the pid into the cgroup.procs file. Freezer I would only implement once we actually use it e.g. if we decide to implement the pause command.

**Comment by utam0k** [comment]
@Furisto @tsturzl 
I updated the description of this issue. Can you please check if it is correct?

**Comment by tsturzl** [comment]
@utam0k This looks good. I'm not seeing any missing subsystems that I'm aware of.

**Comment by Furisto** [comment]
@utam0k Fine from my site as well

**Comment by thinking-tower** [comment]
@utam0k I'd like to work on perf_event!

**Comment by utam0k** [comment]
@thinking-tower Sure, I assigned you it.

**Comment by utam0k** [comment]
@thinking-tower There are no integration tests in this controller. So, I would like to add unit tests as much as possible. I'm looking forward to your PR :)

**Comment by duduainankai** [comment]
I would like to have a try on freezer.

**Comment by utam0k** [comment]
> I would like to have a try on freezer.

@duduainankai of course. I assigned you it.

**Comment by yjuba** [comment]
I would like to work on cpuacct.

**Comment by yjuba** [comment]
I overlooked this PR.
You can forget about my earlier comment.

https://github.com/containers/youki/pull/72

**Comment by utam0k** [comment]
@yjuba Thank you for your interest. There is also a v2 with a similar challenge, what about that one?

**Comment by yjuba** [comment]
@utam0k 
Thank you for your replies.
I will try to work on cpuacct (v2).

**Comment by Furisto** [comment]
Hey @yjuba, you can have cpuacct if you want it. @PeterYordanov unfortunately doesn't have the time to complete it anymore.

**Comment by yjuba** [comment]
@Furisto 
Thank you for your replies.
I will try to work on v1-cpuacct.

**Comment by utam0k** [comment]
@thinking-tower Do you have any problem? Can I help you?

**Comment by utam0k** [comment]
@thinking-tower I'm sorry, but since there seems to be no response, I'm going to remove the assignment.

**Comment by utam0k** [comment]
@fbrv Are you interested in implementing `perf_event`?

**Comment by fbrv** [comment]
It should be pretty easy to implement, just writing the PID in the ```cgroup.procs``` file.

**Comment by utam0k** [comment]
This issue was completed!
Special thanks @0xdco @reynn @tsturzl @Furisto @yjuba @fbrv @duduainankai

**Comment by thinking-tower** [comment]
@utam0k no worries, thanks for the opportunity!
